### ISSUE TITLE
Please add dark mode

### ISSUE THREAD

**Issue by ghost** [ubports/system-settings#121]
SuruDark works already good within the app. Would be great having the choice in the settings. Like in the Messaging App.

**Comment by hummlbach** [comment]
I will try to care that all the core apps support Suru Dark, but I wont add switches, as imho its not that sensefull. I would suggest to tag this as help wanted or to close it as wont fix. @bhdouglass what do you think?
That would add a settings-setting-page or something like that btw - funny ;-)

**Comment by dobey** [comment]
Well, there probably shouldn't be per-app settings to use light or dark theme, but rather, if we must have theme support, then should be a global setting (and some changes so the setting is stored properly with the rest of normal system settings, rather than in its own ini file), and should be under "Appearance" or such, along with background and similar settings. This would require quite a bit of work though.

**Comment by bhdouglass** [comment]
I agree with @dobey , this should be a global dark mode setting rather than per app.

**Comment by ghost** [comment]
Yes, SuruDark support should be enough.
